### ISSUE TITLE
species constraints inconsistent

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#634]
### Describe the issue

<img width="1057" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/473023d0-703d-4ce1-8d96-eb40b8366ab3">

The form allows me to enter any species that follows the structure of a binomial Latin name. However, proceeding requires that the name is on a list of approved names.

I would like to be able to proceed even with a species name that is not on this list. I know  "Monkey monkey" is not a valid name, but I don't want the GUIDE to prohibit the creation of NWB files from new species

### Steps to Reproduce

See above

### Operating System

OSX

### GUIDE Version

main branch

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
> I would like to be able to proceed even with a species name that is not on this list.

This list comes from DANDI API itself - without this check, the user could create an NWB file that can not be uploaded to DANDI

Instead, how about a button or pop-up in this event that instructs / redirects the user to request DANDI add support for the new species?

**Comment by bendichter** [comment]
I really dislike that DANDI does this. Doesn't DANDI allow for NCBITaxon id instead?

**Comment by CodyCBakerPhD** [comment]
Yes, and I believe that works currently in the GUIDE (since it relies on the Inspector check for that, which also should allow it)

**Comment by bendichter** [comment]
I tried the NCBITaxon iri for Mantis shrimp (http://purl.obolibrary.org/obo/NCBITaxon_280675) and got the same error:

<img width="1265" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/727483f5-5282-4274-a4ff-9c8b599cb6ae">

**Comment by bendichter** [comment]
Also, the error message does not indicate that this is possible

**Comment by CodyCBakerPhD** [comment]
OK, thanks for checking - looks like that got intercepted by a form validation before it hit the Inspector check

@garrettmflynn The check for species on both this page and the subject species table should allow for the last part of this regex if not in the enum: https://github.com/NeurodataWithoutBorders/nwbinspector/blob/2b0b73a6bf6a6e522d8e20b144476a1b9a684afd/src/nwbinspector/checks/nwbfile_metadata.py#L17

**Comment by bendichter** [comment]
<img width="1277" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/46d79713-b786-460e-a95f-e2081111b6cf">

@garrettmflynn is this supposed to work now?

**Comment by bendichter** [comment]
@garrettmflynn also, could you please change this hint to indicate that the NCBITaxon approach is an option? 

<img width="739" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/712e6642-631f-43a8-b00c-85f969d7e302">

**Comment by CodyCBakerPhD** [comment]
@bendichter You'll likely have to update your NeuroConv installation in your `nwb-guide` environment; the error you see is actually stemming from the regex validation in the NWB Converter

`pip install -U git+https://github.com/catalystneuro/neuroconv.git@main`

**Comment by CodyCBakerPhD** [comment]
Likewise the message is directly from the NWB Inspector: see https://github.com/NeurodataWithoutBorders/nwbinspector/pull/439

**Comment by bendichter** [comment]
OK, now I get "Error preloading Flask imports"

<img width="1274" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/0466b830-0327-44f7-9edb-05afe9d86def">


Is that expected?

**Comment by CodyCBakerPhD** [comment]
Traceback from dev console? It might be a conflict with something. Oh, I bet it's a Pydantic conflict.

Probably easiest to just regenerate a fresh `nwb-guide` environment altogether

**Comment by bendichter** [comment]
yup

```pytb
Traceback (most recent call last):
  File "/Users/bendichter/dev/nwb-guide/pyflask/apis/neuroconv.py", line 50, in get
    **get_all_interface_info(),
  File "/Users/bendichter/dev/nwb-guide/pyflask/manageNeuroconv/manage_neuroconv.py", line 241, in get_all_interface_info
    from neuroconv.datainterfaces import interface_list
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/neuroconv/__init__.py", line 1, in <module>
    from .basedatainterface import BaseDataInterface
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/neuroconv/basedatainterface.py", line 11, in <module>
    from .tools.nwb_helpers import make_nwbfile_from_metadata, make_or_load_nwbfile
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/neuroconv/tools/__init__.py", line 9, in <module>
    from .nwb_helpers import get_module
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/neuroconv/tools/nwb_helpers/__init__.py", line 7, in <module>
    from ._backend_configuration import get_default_backend_configuration
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/neuroconv/tools/nwb_helpers/_backend_configuration.py", line 7, in <module>
    from ._configuration_models._hdf5_backend import HDF5BackendConfiguration
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/neuroconv/tools/nwb_helpers/_configuration_models/_hdf5_backend.py", line 8, in <module>
    from ._base_backend import BackendConfiguration
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/neuroconv/tools/nwb_helpers/_configuration_models/_base_backend.py", line 9, in <module>
    from ._base_dataset_io import DatasetIOConfiguration
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/neuroconv/tools/nwb_helpers/_configuration_models/_base_dataset_io.py", line 140, in <module>
    class DatasetIOConfiguration(BaseModel, ABC):
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/neuroconv/tools/nwb_helpers/_configuration_models/_base_dataset_io.py", line 208, in DatasetIOConfiguration
    def validate_all_shapes(cls, values: Dict[str, Any]) -> Dict[str, Any]:
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/pydantic/deprecated/class_validators.py", line 231, in root_validator
    return root_validator()(*__args)  # type: ignore
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/pydantic/deprecated/class_validators.py", line 237, in root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`.
```

**Comment by bendichter** [comment]
I also got these pip warnings earlier when I upgraded:

```bash
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dandischema 0.8.4 requires pydantic[email]<2.0,>=1.8.1, but you have pydantic 2.6.3 which is incompatible.
neuroconv 0.4.8 requires pydantic<2.0.0,>=1.10.13, but you have pydantic 2.6.3 which is incompatible.
```

**Comment by bendichter** [comment]
OK, I got this working. I did git pulled and local installed neuroconv, then I ran `npm ci`, and now this works.
