### ISSUE TITLE
Upload failed

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#645]
### Describe the issue

<img width="1275" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/2fb05113-a566-423e-ac97-560c3b0e362e">

### Steps to Reproduce

I just went through the tutorial

### Operating System

OSX

### GUIDE Version

main

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by bendichter** [comment]
```pytb
Traceback (most recent call last):
  File "/Users/bendichter/dev/nwb-guide/pyflask/apis/neuroconv.py", line 163, in post
    return upload_project_to_dandi(**upload_options)
  File "/Users/bendichter/dev/nwb-guide/pyflask/manageNeuroconv/manage_neuroconv.py", line 627, in upload_project_to_dandi
    return automatic_dandi_upload(
  File "/Users/bendichter/dev/neuroconv/src/neuroconv/tools/data_transfers/_dandi.py", line 60, in automatic_dandi_upload
    from dandi.download import download as dandi_download
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/dandi/download.py", line 22, in <module>
    from dandischema.models import DigestType
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/dandischema/__init__.py", line 2, in <module>
    from .metadata import migrate, validate
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/dandischema/metadata.py", line 17, in <module>
    from . import models
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/dandischema/models.py", line 24, in <module>
    from .digests.zarr import ZARR_CHECKSUM_PATTERN, parse_directory_digest
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/dandischema/digests/zarr.py", line 164, in <module>
    EMPTY_CHECKSUM = ZarrJSONChecksumSerializer().generate_listing(ZarrChecksums()).digest
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/dandischema/digests/zarr.py", line 153, in generate_listing
    digest = self.aggregate_digest(checksums)
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/dandischema/digests/zarr.py", line 112, in aggregate_digest
    content = checksums.json(**ENCODING_KWARGS)  # type: ignore[arg-type]
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/pydantic/main.py", line 1056, in json
    raise TypeError('`dumps_kwargs` keyword arguments are no longer supported.')
TypeError: `dumps_kwargs` keyword arguments are no longer supported.
```

**Comment by bendichter** [comment]
trying updating dandischema...

**Comment by bendichter** [comment]
this appears to have worked

**Comment by CodyCBakerPhD** [comment]
If you haven't already, I recommend generating an entire fresh `nwb-guide` conda environment. A lot of dependencies have updated depending on the last time you set it up
