### ISSUE TITLE
Error: Check Alignment when using SpikeGLXConverter

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwb-guide#648]
### Describe the issue

```pytb
Traceback (most recent call last):
  File "/Users/bendichter/dev/nwb-guide/pyflask/apis/neuroconv.py", line 121, in post
    return get_interface_alignment(neuroconv_api.payload)
  File "/Users/bendichter/dev/nwb-guide/pyflask/manageNeuroconv/manage_neuroconv.py", line 445, in get_interface_alignment
    converter = instantiate_custom_converter(info["source_data"], info["interfaces"])
  File "/Users/bendichter/dev/nwb-guide/pyflask/manageNeuroconv/manage_neuroconv.py", line 283, in instantiate_custom_converter
    return CustomNWBConverter(source_data)
  File "/Users/bendichter/dev/neuroconv/src/neuroconv/nwbconverter.py", line 70, in __init__
    self.data_interface_objects = {
  File "/Users/bendichter/dev/neuroconv/src/neuroconv/nwbconverter.py", line 71, in <dictcomp>
    name: data_interface(**source_data[name])
  File "/Users/bendichter/dev/neuroconv/src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxconverter.py", line 78, in __init__
    interface = SpikeGLXRecordingInterface(file_path=file_path)
  File "/Users/bendichter/dev/neuroconv/src/neuroconv/datainterfaces/ecephys/spikeglx/spikeglxdatainterface.py", line 60, in __init__
    super().__init__(
  File "/Users/bendichter/dev/neuroconv/src/neuroconv/datainterfaces/ecephys/baserecordingextractorinterface.py", line 38, in __init__
    self.recording_extractor = self.get_extractor()(**source_data)
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/spikeinterface/extractors/neoextractors/spikeglx.py", line 53, in __init__
    NeoBaseRecordingExtractor.__init__(
  File "/Users/bendichter/opt/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/spikeinterface/extractors/neoextractors/neobaseextractor.py", line 217, in __init__
    assert stream_id in stream_ids, f"stream_id {stream_id} is not in {stream_ids}"
AssertionError: stream_id imec0.lf is not in []
```

### Steps to Reproduce

Do the tutorial, using `SpikeGLXConverter`, and click "Check Alignment"

### Operating System

OSX

### GUIDE Version

main branch

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by bendichter** [comment]
Also when trying to click "Next"

<img width="1277" alt="image" src="https://github.com/NeurodataWithoutBorders/nwb-guide/assets/844306/9cd0a685-3305-46c7-bedd-5b7b8311ae3c">

**Comment by CodyCBakerPhD** [comment]
Can you expand the accordions? Did the locate data helper find all the paths? Curious what values you have there

**Comment by bendichter** [comment]
The Check Alignment button just didn't work

**Comment by garrettmflynn** [comment]
So we intended for the tutorial to be run using the SpikeGLXRecordingInterface (file_path) rather than the SpikeGLXConverter (folder_path) because we're not working with multi-stream data, though I agree that this choice should definitely still work in practice. 

@bendichter It appears that you should have selected `~/NWB_GUIDE/test-data/data/spikeglx/Session1_g0` as the filepath for the converter—though we don't provide great pointers for which directory to choose for this case. I've done this manually and I'm able to get past the Source Data page, and can replicate your error by manually selecting other directories.

@CodyCBakerPhD How should we ensure that users know what path to select for the converters?

**Comment by bendichter** [comment]
ah, ok, I'll try selecting that instead. The newly merged PR here should help with indicating to users precisely which file or folder to select. https://github.com/catalystneuro/neuroconv/pull/771

**Comment by CodyCBakerPhD** [comment]
I suspected that was the cause; so neither the 'Check Alignment' nor 'Next' button should work on this page if the incorrect path is specified

The error message that will popup depends on the interfaces with the wrong path specified. Perhaps we can define some better interceptions before they reach SI/ROIExtractors, etc. But not much that can be done about this on the GUIDE itself

**Comment by bendichter** [comment]
yes, I can confirm that this was the issue. Thanks for the clarification, @garrettmflynn
