### ISSUE TITLE
Generating test data in local Mac build has error

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#720]
### Describe the issue

On a local deployment, I got the error `Request to generate failed: No module named 'scipy.special._cdflib'` when trying to generate the test data.

### Steps to Reproduce

1. I deleted my local `~/NWB_GUIDE` folder. 
2. I ran `npm deploy:mac` but stopped execution during the code signing stage (takes forever and is not necessary for local installs). 
3. I went to settings and clicked Generate.

Developer console log:
```
index-f4fbaab8.js:33736 [main-process]: 
extract waveforms shared_memory multi buffer:   0%|          | 0/3 [00:00<?, ?it/s]
(anonymous) @ index-f4fbaab8.js:33736
index-f4fbaab8.js:33736 [main-process]: 
extract waveforms shared_memory multi buffer:  33%|###3      | 1/3 [00:00<00:00,  7.42it/s]
(anonymous) @ index-f4fbaab8.js:33736
index-f4fbaab8.js:33736 [main-process]: 
extract waveforms shared_memory multi buffer:  67%|######6   | 2/3 [00:00<00:00,  7.31it/s]
(anonymous) @ index-f4fbaab8.js:33736
index-f4fbaab8.js:33736 [main-process]: 
extract waveforms shared_memory multi buffer: 100%|##########| 3/3 [00:00<00:00,  7.43it/s]
extract waveforms shared_memory multi buffer: 100%|##########| 3/3 [00:00<00:00,  7.40it/s]
(anonymous) @ index-f4fbaab8.js:33736
index-f4fbaab8.js:33736 [main-process]: 

(anonymous) @ index-f4fbaab8.js:33736
index-f4fbaab8.js:33736 [main-process]: 
extract waveforms shared_memory multi buffer:   0%|          | 0/3 [00:00<?, ?it/s]
(anonymous) @ index-f4fbaab8.js:33736
index-f4fbaab8.js:33736 [main-process]: 
extract waveforms shared_memory multi buffer:  33%|###3      | 1/3 [00:00<00:00,  7.59it/s]
(anonymous) @ index-f4fbaab8.js:33736
index-f4fbaab8.js:33736 [main-process]: 
extract waveforms shared_memory multi buffer:  67%|######6   | 2/3 [00:00<00:00,  7.63it/s]
(anonymous) @ index-f4fbaab8.js:33736
index-f4fbaab8.js:33736 [main-process]: 
extract waveforms shared_memory multi buffer: 100%|##########| 3/3 [00:00<00:00,  7.64it/s]
extract waveforms shared_memory multi buffer: 100%|##########| 3/3 [00:00<00:00,  7.63it/s]

(anonymous) @ index-f4fbaab8.js:33736
index-f4fbaab8.js:33736 [main-process]: [2024-04-03 10:51:52,074] ERROR in app: Exception on /data/generate [POST]
Traceback (most recent call last):
  File "apis/data.py", line 30, in post
  File "manageNeuroconv/manage_neuroconv.py", line 1089, in generate_test_data
  File "spikeinterface/preprocessing/filter.py", line 191, in __init__
  File "spikeinterface/preprocessing/filter.py", line 74, in __init__
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "scipy/signal/__init__.py", line 307, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "scipy/signal/windows/__init__.py", line 42, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "scipy/signal/windows/_windows.py", line 7, in <module>
  File "scipy/__init__.py", line 134, in __getattr__
  File "importlib/__init__.py", line 127, in import_module
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "scipy/special/__init__.py", line 777, in <module>
  File "scipy/special/_ufuncs.pyx", line 1, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._cdflib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask/app.py", line 1484, in full_dispatch_request
  File "flask/app.py", line 1469, in dispatch_request
  File "flask_restx/api.py", line 404, in wrapper
  File "flask/views.py", line 109, in view
  File "flask_restx/resource.py", line 46, in dispatch_request
  File "apis/data.py", line 33, in post
  File "flask_restx/namespace.py", line 153, in abort
  File "flask_restx/errors.py", line 28, in abort
  File "flask/helpers.py", line 277, in abort
  File "werkzeug/exceptions.py", line 861, in __call__
werkzeug.exceptions.InternalServerError: 500 Internal Server Error: The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

### Operating System

Mac M1

### GUIDE Version

main

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by rly** [comment]
I will try adding `scipy.special._cdflib` to `nwb-guide.spec` and rebuild.

**Comment by rly** [comment]
Adding `*collect_submodules('scipy.special._cdflib')` to `hiddenimports` in `nwb-guide.spec` seems to fix the error, even though the log says:
```
771 DEBUG: Collecting submodules for scipy.special.cython_special
1152 DEBUG: collect_submodules - scipy.special.cython_special is not a package.
1320 DEBUG: Collecting submodules for scipy.special._cdflib
1486 DEBUG: collect_submodules - scipy.special._cdflib is not a package
```

Maybe we should use `*collect_submodules('scipy.special')` instead?

**Comment by CodyCBakerPhD** [comment]
We just ran into this on Windows specifically on the other PR - I down pinned to 1.12.0

If it affects M1+ macs (not in CI) then I'd say just add it there to and well circle around to how to deal with future scipy versions in a follow up
