### ISSUE TITLE
[Bug]: Standalone validation page fails on a single file

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwb-guide#860]
### Describe the issue

```python
Traceback (most recent call last):
  File "flask\app.py", line 1484, in full_dispatch_request
  File "flask\app.py", line 1469, in dispatch_request
  File "flask_restx\api.py", line 404, in wrapper
  File "flask\views.py", line 109, in view
  File "flask_restx\resource.py", line 46, in dispatch_request
  File "namespaces\neuroconv.py", line 206, in post
  File "manageNeuroconv\manage_neuroconv.py", line 1400, in inspect_nwb_file
TypeError: inspect_nwbfile() got an unexpected keyword argument 'request_id'
```

### Steps to Reproduce

Standalone inspection page, select a single file

### Operating System

All

### GUIDE Version

v1.0.0

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
Perhaps an issue with the payload in the file vs. directory case?
