### ISSUE TITLE
Broken imports using latest nwbinspector

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwb-guide#919]
### Describe the issue

From [end-to-end tests](https://github.com/NeurodataWithoutBorders/nwb-guide/actions/runs/10527059741/job/29169356131):
```
Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/runner/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/runner/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/flask_restx/api.py", line 404, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/runner/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/runner/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/flask_restx/resource.py", line 46, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/runner/work/nwb-guide/nwb-guide/src/pyflask/namespaces/neuroconv.py", line 179, in post
    return inspect_all(url, neuroconv_namespace.payload)
  File "/home/runner/work/nwb-guide/nwb-guide/src/pyflask/manageNeuroconv/manage_neuroconv.py", line 1564, in inspect_all
    from nwbinspector.inspector_tools import format_messages, get_report_header
  File "/home/runner/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/nwbinspector/inspector_tools/__init__.py", line 12, in <module>
    from .._organization import organize_messages, _get_report_header
ImportError: cannot import name '_get_report_header' from 'nwbinspector._organization' (/home/runner/miniconda3/envs/nwb-guide/lib/python3.9/site-packages/nwbinspector/_organization.py)
```

With nwbinspector 0.5.1

### Steps to Reproduce

Run end-to-end tests with latest nwbinspector

### Operating System

all

### GUIDE Version

main

### Code of Conduct

Yes

### Did you confirm this issue was not already reported?

Yes

**Comment by CodyCBakerPhD** [comment]
Already fixing/fixed in #918
